export const typewriterSoundVolume = 0.2; // Volume du son de la machine à écrire
export const clickSoundVolume = 0.2; // Volume du son de clic
export const backgroundMusicVolume = 0.1; // Volume de la musique de fond
export const startSoundVolume = 0.4; // Volume du son de démarrage
export const loadingSoundVolume = 0.2; // Volume du son de chargement
export const typewriterSpeed = 50; // Vitesse de la machine à écrire (ms par lettre)
export const initialMessageDelay = 10000; // Délai avant d'afficher le message initial (ms)
export const dialogueStartDelay = 5000; // Délai avant de commencer le dialogue (ms)
export const fadeOutDuration = 500; // Durée de l'effet de fondu (ms)
